name: GitHub Pages

on:
  push:
    branches: [main]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global user.name "Andrey Kuzmin"
      - run: git config --global user.email "hi@unsoundscapes.com"

      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command elm-format --validate .
      - run: nix develop --command elm-review
      - run: nix develop --command elm-test

      - uses: actions/checkout@v3
        with:
          path: gh-pages
          ref: gh-pages
      - run: nix develop --command ./scripts/gh-pages.sh
