name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Confirm the new version"
        required: true
    branches: [main]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git config --global user.name "Andrey Kuzmin"
      - run: git config --global user.email "unsoundscapes@gmail.com"

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.elm
          key: ${{ runner.os }}-cache

      - run: npm install -g elm@latest-0.19.1 elm-test@0.19.1-revision6 elm-review@2.5.0 elm-format@0.8.5

      - run: elm-format --validate .

      - run: elm-review

      - run: elm-test

      - run: ./scripts/elm-publish.sh ${{ github.event.inputs.version }}

      - uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages
      - run: ./scripts/gh-pages.sh ${{ github.event.inputs.version }}
